### ISSUE TITLE
Add Bcrypt

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-opendj#2]
This project has an MIT license Bcrypt implementation. Perhaps we could add this to OpenDJ.

https://github.com/sammonsjl/ldapchai-opendj/blob/master/src/com/novell/ldapchai/util/BCrypt.java

We'd have to figure our if there are any other dependencies in the project. If we great the project  for SSHA or MD5 we can probably figure out all the places we need to update.

**Comment by yurem** [comment]
Implemented. We will include it into 3.1.4
